name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: parisk/poetry

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/parisk/poetry:latest
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
